name: Docker Compose Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Show containers
        run: docker compose ps

      - name: Wait for application
        run: sleep 5

      - name: Test Nginx
        run: curl --fail http://localhost

      - name: Test load balancing
        run: |
          for i in {1..6}; do
            curl --fail http://localhost
          done

      - name: Show logs
        if: always()
        run: docker compose logs

      - name: Stop containers
        if: always()
        run: docker compose down
